#cloud-config
package_upgrade: true
packages:
  - tmux
  - unzip
  - zip
  - git
  - python3
  - python3-pip
  - python3-venv
runcmd:
  - 'cd /root && git clone https://github.com/boxyfour/autozenith && cd autozenith/src/assets/install.sh'
  - 'cd /root/ZenithProxy/assets'
  - 'venv/bin/python3 createconfig.py TOKEN CHANNEL ROLE RELAY'
  - 'cd /root/ZenithProxy && rm -r assets'