#cloud-config
package_upgrade: true
packages:
  - tmux
  - zsh
  - unzip
  - zip
  - git
  - python3
  - python3-pip
  - python3-venv
runcmd:
  - [runuser, -l, root, -c, 'chsh -s /usr/bin/zsh root']
  - 'cd /root && wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh && chmod +x install.sh'
  - [runuser, -l, root, -c, '/usr/bin/zsh -c "/root/install.sh --unattended"']
  - 'cd /root && mkdir ZenithProxy && cd ZenithProxy && wget https://github.com/rfresh2/ZenithProxy/releases/download/launcher-v3/ZenithProxy-launcher-linux-amd64.zip && unzip ZenithProxy-launcher-linux-amd64.zip'
  - 'cd /root/ZenithProxy && git clone https://github.com/boxyfour/autozenith && cd autozenith && mv autozenith/src/assets .../ && rm -r autozenith'
  - '/root/ZenithProxy/autozenith/src/assets/install.sh && venv/bin/python createconfig.py TOKEN CHANNEL ROLE'
  - 'cd /root/ZenithProxy && rm -r assets'
  - 'tmux && cd /root/ZenithProxy && ./launch'
  - 'rm /root/install.sh'