#cloud-config
package_upgrade: true
packages:
  - tmux
  - unzip
  - zip
  - git
  - python3
  - python3-pip
  - python3-venv
  - openjdk-21-jdk
runcmd:
  - 'cd /root && git clone https://github.com/boxyfour/autozenith && cd autozenith/src/assets && chmod +x install.sh'
  - [runuser, -l, root, -c, '/bin/bash -c "/root/autozenith/src/assets/install.sh"']
  - 'cd /root/ZenithProxy/assets'
  - 'venv/bin/python3 createconfig.py TOKEN CHANNEL ROLE'
  - 'cd /root/ZenithProxy && rm -r assets'
  - 'reboot'